<?php

// Register Custom Post Type
function drinks_post_type() {
  $labels = array(
    'name'                  => __('Drinks', 'hi5'),
    'singular_name'         => __('Drink', 'hi5'),
    'menu_name'             => __('Drinks', 'hi5'),
    'name_admin_bar'        => __('Count', 'hi5'), //TODO
    'archives'              => __('Drink Archives', 'hi5'),
    'parent_item_colon'     => __('Drink Store', 'hi5'),
    'all_items'             => __('All Drinks', 'hi5'),
    'add_new_item'          => __('Add New Drink', 'hi5'),
    'add_new'               => __('Add New Drink', 'hi5'),
    'new_item'              => __('New Drink', 'hi5'),
    'edit_item'             => __('Edit Drink', 'hi5'),
    'update_item'           => __('Update Drink', 'hi5'),
    'view_item'             => __('View Drink', 'hi5'),
    'search_items'          => __('Search Drink', 'hi5'),
    'not_found'             => __('Drink Not found', 'hi5'),
    'not_found_in_trash'    => __('Drink Not found in Trash', 'hi5'),
    'featured_image'        => __('Featured Image', 'hi5'),
    'set_featured_image'    => __('Set featured image', 'hi5'),
    'remove_featured_image' => __('Remove featured image', 'hi5'),
    'use_featured_image'    => __('Use as featured image', 'hi5'),
    'insert_into_item'      => __('Insert into Drink', 'hi5'),
    'uploaded_to_this_item' => __('Uploaded to this Drink', 'hi5'),
    'items_list'            => __('Drink list', 'hi5'),
    'items_list_navigation' => __('Drink list navigation', 'hi5'),
    'filter_items_list'     => __('Filter Drink list', 'hi5'),
  );

  $args = array(
    'label'                 => __('Drink'),
    'description'           => __('Drinks'),
    'labels'                => $labels,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'show_in_rest'			    => true,    
    // 'rewrite'           => array( 'slug' => 'drink_family', 'with_front' => false ),
    // 'rewrite' => array(
    //   'slug'       => 'drinks',//TODO %drink_family%',
    //   'with_front' => true
    // ),
    // 'menu_position'         => 3,
    'menu_icon'             => 'dashicons-screenoptions',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'show_admin_column'     => true,
    'show_admin_column'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'page',
  );

  register_post_type( 'drink', $args );

  //Taxonomy - Availability
  $tax_labels = array(
    'name'                  => 'Drink Availability',
    'singular_name'         => 'Drink Availability',
    'menu_name'             => 'Drink Availabilities',
    'name_admin_bar'        => 'Drink Availabilities',
    'archives'              => 'Drink Availability Archives',
    'parent_item_colon'     => 'Parent Drink Availability:',
    'all_items'             => 'All Drink Availabilities',
    'add_new_item'          => 'Add New Drink Availability',
    'add_new'               => 'Add New Drink Availability',
    'new_item'              => 'New Drink Availability',
    'edit_item'             => 'Edit Drink Availability',
    'update_item'           => 'Update Drink Availability',
    'view_item'             => 'View Drink Availability',
    'search_items'          => 'Search Drink Availability',
    'not_found'             => 'Not found',
    'not_found_in_trash'    => 'Not found in Trash',
    'featured_image'        => 'Featured Image',
    'set_featured_image'    => 'Set featured image',
    'remove_featured_image' => 'Remove featured image',
    'use_featured_image'    => 'Use as featured image',
    'insert_into_item'      => 'Insert into Drink Availability',
    'uploaded_to_this_item' => 'Uploaded to this Drink Availability',
    'items_list'            => 'Drink Availabilities list',
    'items_list_navigation' => 'Drink Availabilities list navigation',
    'filter_items_list'     => 'Filter Drink Availabilities list',
  );
  $tax_args = array(
    'label'                 => 'Drink Availabilities',
    'description'           => 'Drink Availabilities',
    'labels'                => $tax_labels,
    'show_in_rest'          => true,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
    'hierarchical'          => true,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'menu_icon'             => 'dashicons-tickets-alt',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'show_admin_column'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    // 'rewrite'
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'page',
  );
  register_taxonomy( 'drink_availability', 'drink', $tax_args );
  
  //Taxonomy - Family
  $tax_labels = array(
    'name'                  => 'Drink Family',
    'singular_name'         => 'Drink Family',
    'menu_name'             => 'Drink Families',
    'name_admin_bar'        => 'Drink Families',
    'archives'              => 'Drink Family Archives',
    'parent_item_colon'     => 'Parent Drink Family:',
    'all_items'             => 'All Drink Families',
    'add_new_item'          => 'Add New Drink Family',
    'add_new'               => 'Add New Drink Family',
    'new_item'              => 'New Drink Family',
    'edit_item'             => 'Edit Drink Family',
    'update_item'           => 'Update Drink Family',
    'view_item'             => 'View Drink Family',
    'search_items'          => 'Search Drink Family',
    'not_found'             => 'Not found',
    'not_found_in_trash'    => 'Not found in Trash',
    'featured_image'        => 'Featured Image',
    'set_featured_image'    => 'Set featured image',
    'remove_featured_image' => 'Remove featured image',
    'use_featured_image'    => 'Use as featured image',
    'insert_into_item'      => 'Insert into Drink Family',
    'uploaded_to_this_item' => 'Uploaded to this Drink Family',
    'items_list'            => 'Drink Familys list',
    'items_list_navigation' => 'Drink Familys list navigation',
    'filter_items_list'     => 'Filter Drink Familys list',
  );
  $tax_args = array(
    'label'                 => 'Drink Families',
    'description'           => 'Drink Families',
    'labels'                => $tax_labels,
    'show_in_rest'          => true,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
    'hierarchical'          => true,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'menu_icon'             => 'dashicons-tickets-alt',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'show_admin_column'     => true,
    'can_export'            => true,
    'has_archive'           => true,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'page',
    // 'rewrite' => array( 'slug' => '/', 'with_front' => false )
    // 'rewrite'               => array('slug' => 'drinks', 'with_front' => false),
		// 'rewrite'               => array(
		// 	// 'slug'       => '/drink_family/%drink_family%',
		// 	'with_front' => false
    // ),
  );
  register_taxonomy( 'drink_family', 'drink', $tax_args );
  
  //Taxonomy - Store
  $tax_labels = array(
    'name'                  => 'Store',
    'singular_name'         => 'Store',
    'menu_name'             => 'Stores',
    'name_admin_bar'        => 'Stores',
    'archives'              => 'Store Archives',
    'parent_item_colon'     => 'Parent Store:',
    'all_items'             => 'All Stores',
    'add_new_item'          => 'Add New Store',
    'add_new'               => 'Add New Store',
    'new_item'              => 'New Store',
    'edit_item'             => 'Edit Store',
    'update_item'           => 'Update Store',
    'view_item'             => 'View Store',
    'search_items'          => 'Search Store',
    'not_found'             => 'Not found',
    'not_found_in_trash'    => 'Not found in Trash',
    'featured_image'        => 'Featured Image',
    'set_featured_image'    => 'Set featured image',
    'remove_featured_image' => 'Remove featured image',
    'use_featured_image'    => 'Use as featured image',
    'insert_into_item'      => 'Insert into Store',
    'uploaded_to_this_item' => 'Uploaded to this Store',
    'items_list'            => 'Stores list',
    'items_list_navigation' => 'Stores list navigation',
    'filter_items_list'     => 'Filter Stores list',
  );
  $tax_args = array(
    'label'                 => 'Stores',
    'description'           => 'Stores',
    'labels'                => $tax_labels,
    'show_in_rest'          => true,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
    'hierarchical'          => true,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'menu_icon'             => 'dashicons-tickets-alt',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'show_admin_column'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'page',
  );
  register_taxonomy( 'drink_store', 'drink', $tax_args );

    
  //Taxonomy - Type
  $tax_labels = array(
    'name'                  => 'Drink Type',
    'singular_name'         => 'Drink Type',
    'menu_name'             => 'Drink Type',
    'name_admin_bar'        => 'Drink Type',
    'archives'              => 'Drink Type Archives',
    'parent_item_colon'     => 'Parent Drink Type:',
    'all_items'             => 'All Drink Type',
    'add_new_item'          => 'Add New Drink Type',
    'add_new'               => 'Add New Drink Type',
    'new_item'              => 'New Drink Type',
    'edit_item'             => 'Edit Drink Type',
    'update_item'           => 'Update Drink Type',
    'view_item'             => 'View Drink Type',
    'search_items'          => 'Search Drink Type',
    'not_found'             => 'Not found',
    'not_found_in_trash'    => 'Not found in Trash',
    'featured_image'        => 'Featured Image',
    'set_featured_image'    => 'Set featured image',
    'remove_featured_image' => 'Remove featured image',
    'use_featured_image'    => 'Use as featured image',
    'insert_into_item'      => 'Insert into Drink Type',
    'uploaded_to_this_item' => 'Uploaded to this Drink Type',
    'items_list'            => 'Drink Type list',
    'items_list_navigation' => 'Drink Type list navigation',
    'filter_items_list'     => 'Filter Drink Type list',
  );
  $tax_args = array(
    'label'                 => 'Drink Type',
    'description'           => 'Drink Type',
    'labels'                => $tax_labels,
    'show_in_rest'          => true,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
    'hierarchical'          => true,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'menu_icon'             => 'dashicons-tickets-alt',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'show_admin_column'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'page',
  );
  register_taxonomy( 'drink_type', 'drink', $tax_args );
  
  
}
add_action( 'init', 'drinks_post_type', 0 );